import os

os.system("pip install autopep8")
os.system("pip install MouseInfo")
os.system("pip install numpy")
os.system("pip install opencv-python")
os.system("pip install Pillow")
os.system("pip install PyAutoGUI")
os.system("pip install pycodestyle")
os.system("pip install PyGetWindow")
os.system("pip install PyMsgBox")
os.system("pip install pyperclip")
os.system("pip install PyRect")
os.system("pip install PyScreeze")
os.system("pip install pytweening")
os.system("pip install setuptools")
os.system("pip install toml")
print("\n Setup Complete...")